version: '3.8'
services:
  metastore-db:
    image: wlcamargo/mariadb
    container_name: metastore-db
    networks:
      - src_lakehouse
    volumes:
      - metastore-db:/var/lib/mysql
    environment:
      - DB_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
    extra_hosts:
      - "host.docker.internal:host-gateway"

  create-metastore-schema:
    image: wlcamargo/hive-metastore
    container_name: create-metastore-schema
    depends_on:
      - metastore-db
    networks:
      - src_lakehouse
    command: /opt/hive-metastore/bin/schematool --verbose -initSchema -dbType mysql -userName ${DB_ROOT_USER} -passWord ${DB_ROOT_PASSWORD} -url jdbc:mysql://metastore-db:3306/metastore_db?createDatabaseIfNotExist=true
    restart: "on-failure"
    extra_hosts:
      - "host.docker.internal:host-gateway"

  metastore:
    image: wlcamargo/hive-metastore
    container_name: metastore
    depends_on:
      - create-metastore-schema
      - metastore-db
    networks:
      - src_lakehouse
    volumes:
      - ./metastore-site.xml:/opt/hive-metastore/conf/metastore-site.xml
      - ./core-site.xml:/opt/hadoop/etc/hadoop/core-site.xml
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
    command: /opt/hive-metastore/bin/start-metastore -p 9083
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  src_lakehouse:
    external: true

volumes:
  metastore-db:
