version: '3.8'
services:
  trino:
    image: trinodb/trino:405
    container_name: trino
    hostname: trino
    ports:
      - 8080:8080
    volumes:
      - ./conf:/etc/trino
      - ./conf/hive.properties:/etc/trino/catalog/hive.properties
      - ./conf/delta.properties:/etc/trino/catalog/delta.properties
      - ./conf/iceberg.properties:/etc/trino/catalog/iceberg.properties
      - ./conf/postgres.properties:/etc/trino/catalog/postgres.properties
      - ./conf/sqlserver.properties:/etc/trino/catalog/sqlserver.properties
    networks:
      - src_lakehouse
    extra_hosts:
      - "host.docker.internal:host-gateway"


networks:
  src_lakehouse:
    external: true
