coordinator=true
node-scheduler.include-coordinator=true

# Disable HTTP, enable HTTPS
http-server.http.enabled=false
http-server.https.enabled=true
http-server.https.port=8443
http-server.https.keystore.path=/etc/trino/keystore.jks
http-server.https.keystore.key=changeit

# Password authentication
http-server.authentication.type=PASSWORD
password-authenticator.config-files=/etc/trino/password-authenticator.properties

# Internal communication (HTTPS required)
internal-communication.shared-secret=segredo123
internal-communication.https.required=true

discovery-server.enabled=true
discovery.uri=https://trino:8443
